### ISSUE TITLE
Problem registering a runner

### ISSUE THREAD

**Issue by ayufan** [evanlucas/gcr#1]
```
ayufan@Kamils-MacBook-Air ~/.config> cat gcr.json 
{
  "buildDir": "/tmp/builds",
  "git": "/usr/bin/git"
}

[?] Please enter your GitLab CI url: https://***
[?] Please enter your GitLab CI Registration Token: ***
gcr http POST undefined/api/v1/runners/register.json
gcr ERR! [register] Error: Invalid protocol
gcr ERR! [register]     at Request.self._buildRequest (/usr/local/lib/node_modules/gcr/node_modules/request/request.js:336:53)
gcr ERR! [register]     at Request.init (/usr/local/lib/node_modules/gcr/node_modules/request/request.js:503:10)
gcr ERR! [register]     at new Request (/usr/local/lib/node_modules/gcr/node_modules/request/request.js:97:8)
gcr ERR! [register]     at request (/usr/local/lib/node_modules/gcr/node_modules/request/index.js:50:11)
gcr ERR! [register]     at Function.request.post (/usr/local/lib/node_modules/gcr/node_modules/request/index.js:116:27)
gcr ERR! [register]     at Client.registerRunner (/usr/local/lib/node_modules/gcr/lib/client.js:55:11)
gcr ERR! [register]     at /usr/local/lib/node_modules/gcr/bin/cmd.js:63:18
gcr ERR! [register]     at fs.js:266:14
gcr ERR! [register]     at Object.oncomplete (fs.js:107:15)
gcr ERR! [register]  error registering [Error: Invalid protocol]
```

**Comment by CesarLanderos** [comment]
i am having this problem, looks like its striping the `/ci` when making the request, i am running gitlab 8.0.3, and after another try (setting ssl to false), just tries to find builds from that same wrong url, i cant find a way to try to register aggain the runner (i still have 0 runners in my gitlab ci server)

```
[?] Please enter your GitLab CI url: https://***/ci
ec] Please enter your GitLab CI Registration Token: *********************
gcr http POST https://***/api/v1/runners/register.json
gcr ERR! [register] Error: DEPTH_ZERO_SELF_SIGNED_CERT
gcr ERR! [register]     at SecurePair.<anonymous> (tls.js:1381:32)
gcr ERR! [register]     at SecurePair.emit (events.js:92:17)
gcr ERR! [register]     at SecurePair.maybeInitFinished (tls.js:980:10)
gcr ERR! [register]     at CleartextStream.read [as _read] (tls.js:472:13)
gcr ERR! [register]     at CleartextStream.Readable.read (_stream_readable.js:341:10)
gcr ERR! [register]     at EncryptedStream.write [as _write] (tls.js:369:25)
```
