### ISSUE TITLE
Unhandled Error Event

### ISSUE THREAD

**Issue by Arcath** [evanlucas/gcr#19]
Running Windows 10 Pro x64 I get this error when trying to run a build:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /bin/bash ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
```

GitLab CI's log shows:

```
C:\Program Files (x86)\git\cmd\git.EXE clone https://gitlab-ci-token:xxxxxx@gitlab.com/myproject.git project-10634
Cloning into 'project-10634'...

C:\Program Files (x86)\git\cmd\git.EXE checkout e7432a8931491ccd989ec56eda20d3168626c445
Note: checking out 'e7432a8931491ccd989ec56eda20d3168626c445'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e7432a8... Fix up the home page, release 0.1.0
```

**Comment by evanlucas** [comment]
What node version are you running?

**Comment by Arcath** [comment]
Node v0.12.0

**Comment by evanlucas** [comment]
hm, mind trying with the latest node (v4.x). It tends to have better error messages.

**Comment by Arcath** [comment]
After updating I get the same issue with different line numbers:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/bash ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by evanlucas** [comment]
intersting...can you try running with the `--loglevel silly` flag?
